# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ACME-PIA-Export
version:      0.16
license:      perl
version_from: Export.pm
installdirs:  site
requires: 
    IO::Socket:                 0


distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
